_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 1
                - 41
                - 55
                - 105
            "2":
                - 1
                - 41
                - 55
                - 105
            "3":
                - 16
                - 23
                - 55
            "4": 3.12.9
            "5": 0.19.8
            "8":
                - 3
                - 5
            "12": 0.19.8
            "13": windows-amd64
artifact_alias:
    value: latest
batch_size:
    value: 8
bbox_interval:
    value: -1
bucket:
    value: ""
cache:
    value: null
cfg:
    value: models/detect/gelan-c.yaml
close_mosaic:
    value: 0
cos_lr:
    value: false
data:
    value: data/helicopter.yaml
data_dict:
    value:
        names:
            "0": helicopter
        nc: 1
        path: C:\Users\Patrick\Documents\WebutviklingRepo\yolov9\data\dataset\helicopter
        train: C:\Users\Patrick\Documents\WebutviklingRepo\yolov9\data\dataset\helicopter\train\images
        val: C:\Users\Patrick\Documents\WebutviklingRepo\yolov9\data\dataset\helicopter\train\images
device:
    value: ""
entity:
    value: null
epochs:
    value: 100
evolve:
    value: null
exist_ok:
    value: false
fixed_lr:
    value: false
flat_cos_lr:
    value: false
freeze:
    value:
        - 0
hyp:
    value:
        anchor_t: 5
        box: 7.5
        cls: 0.5
        cls_pw: 1
        copy_paste: 0.3
        degrees: 0
        dfl: 1.5
        fl_gamma: 0
        fliplr: 0.5
        flipud: 0
        hsv_h: 0.015
        hsv_s: 0.7
        hsv_v: 0.4
        iou_t: 0.2
        lr0: 0.01
        lrf: 0.01
        mixup: 0.15
        momentum: 0.937
        mosaic: 1
        obj: 0.7
        obj_pw: 1
        perspective: 0
        scale: 0.9
        shear: 0
        translate: 0.1
        warmup_bias_lr: 0.1
        warmup_epochs: 3
        warmup_momentum: 0.8
        weight_decay: 0.0005
image_weights:
    value: false
imgsz:
    value: 640
label_smoothing:
    value: 0
local_rank:
    value: -1
min_items:
    value: 0
multi_scale:
    value: false
name:
    value: exp
noautoanchor:
    value: false
noplots:
    value: false
nosave:
    value: false
noval:
    value: false
optimizer:
    value: SGD
patience:
    value: 100
project:
    value: runs\train
quad:
    value: false
rect:
    value: false
resume:
    value: false
save_dir:
    value: runs\train\exp13
save_period:
    value: -1
seed:
    value: 0
single_cls:
    value: false
sync_bn:
    value: false
upload_dataset:
    value: false
weights:
    value: weights/gelan-c.pt
workers:
    value: 1
